"""Procedural ambient bed.

The bed is synthesised rather than generated by a model so that the beat grid is
known by construction — every downbeat lands exactly where we put it, which is
what the arranger needs. See DESIGN.md for the alternatives.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from scipy import signal

SR = 44100


@dataclass(frozen=True)
class Grid:
    """A metrical grid. All times in seconds."""

    bpm: float = 80.0
    beats_per_bar: int = 4
    sr: int = SR

    @property
    def beat(self) -> float:
        return 60.0 / self.bpm

    @property
    def bar(self) -> float:
        return self.beat * self.beats_per_bar

    def bar_start(self, index: int) -> float:
        return index * self.bar

    def samples(self, seconds: float) -> int:
        return int(round(seconds * self.sr))


def _midi_hz(note: float) -> float:
    return 440.0 * 2 ** ((note - 69) / 12.0)


def _env(n: int, attack: float, decay: float, sr: int = SR) -> np.ndarray:
    """Percussive attack/exponential-decay envelope."""
    t = np.arange(n) / sr
    a = np.clip(t / max(attack, 1e-4), 0, 1)
    return a * np.exp(-t / max(decay, 1e-4))


def _add(buf: np.ndarray, sig: np.ndarray, at: int) -> None:
    end = min(len(buf), at + len(sig))
    if end > at:
        buf[at:end] += sig[: end - at]


def _onepole_lp(x: np.ndarray, cutoff: float, sr: int = SR) -> np.ndarray:
    b, a = signal.butter(2, min(cutoff / (sr / 2), 0.99), btype="low")
    return signal.lfilter(b, a, x)


def _reverb(x: np.ndarray, seconds: float = 2.2, mix: float = 0.35, sr: int = SR,
            rng: np.random.Generator | None = None) -> np.ndarray:
    """Convolution reverb against a synthetic exponentially-decaying noise IR."""
    rng = rng or np.random.default_rng(0)
    n = int(seconds * sr)
    t = np.arange(n) / sr
    ir = rng.standard_normal(n) * np.exp(-t * (5.0 / seconds))
    ir[: int(0.02 * sr)] *= np.linspace(0, 1, int(0.02 * sr))  # soften pre-delay
    ir = _onepole_lp(ir, 4000.0, sr)
    ir /= np.abs(ir).sum() / 8
    wet = signal.fftconvolve(x, ir)[: len(x)]
    return (1 - mix) * x + mix * wet


# i - VI - III - VII in A minor: warm, unresolved, loops without drawing attention.
PROGRESSION = [
    [45, 52, 57, 60, 64],  # Am
    [41, 48, 53, 57, 60],  # F
    [48, 55, 60, 64, 67],  # C
    [43, 50, 55, 59, 62],  # G
]
PENTATONIC = [69, 72, 74, 76, 79, 81, 84]  # A minor pentatonic, upper register


def _pad(grid: Grid, n_bars: int, rng: np.random.Generator) -> np.ndarray:
    """Sustained chord wash, one chord per bar, overlapping into the next."""
    total = grid.samples(n_bars * grid.bar) + grid.sr
    out = np.zeros(total)
    dur = grid.bar * 1.6  # overlap so chords bleed into one another
    n = grid.samples(dur)
    t = np.arange(n) / grid.sr
    # Slow swell in, slow fall away.
    env = np.sin(np.pi * np.clip(t / dur, 0, 1)) ** 1.5

    for b in range(n_bars):
        chord = PROGRESSION[b % len(PROGRESSION)]
        voice = np.zeros(n)
        for note in chord:
            for detune in (-0.06, 0.0, 0.06):
                f = _midi_hz(note + detune)
                phase = rng.uniform(0, 2 * np.pi)
                voice += np.sin(2 * np.pi * f * t + phase) / (1 + 0.5 * (note - 45) / 12)
        voice /= len(chord) * 3
        # Gentle filter movement keeps a static chord from sounding synthetic.
        voice = _onepole_lp(voice, 900 + 400 * np.sin(b * 0.7))
        _add(out, voice * env, grid.samples(grid.bar_start(b)))
    return out


def _bass(grid: Grid, n_bars: int) -> np.ndarray:
    total = grid.samples(n_bars * grid.bar) + grid.sr
    out = np.zeros(total)
    n = grid.samples(grid.bar * 0.9)
    t = np.arange(n) / grid.sr
    env = np.clip(t / 0.15, 0, 1) * np.exp(-t / (grid.bar * 0.6))
    for b in range(n_bars):
        root = PROGRESSION[b % len(PROGRESSION)][0] - 12
        f = _midi_hz(root)
        sig = (np.sin(2 * np.pi * f * t) + 0.25 * np.sin(4 * np.pi * f * t)) * env
        _add(out, sig * 0.5, grid.samples(grid.bar_start(b)))
    return out


def _drums(grid: Grid, n_bars: int, rng: np.random.Generator) -> np.ndarray:
    total = grid.samples(n_bars * grid.bar) + grid.sr
    out = np.zeros(total)

    # Soft sub kick with a pitch drop, on beats 1 and 3.
    kn = grid.samples(0.35)
    kt = np.arange(kn) / grid.sr
    kick = np.sin(2 * np.pi * np.cumsum(55 * np.exp(-kt * 18) + 34) / grid.sr)
    kick *= _env(kn, 0.002, 0.12)

    # Rimshot: short filtered noise burst, on the backbeat.
    rn = grid.samples(0.06)
    noise = rng.standard_normal(rn)
    b, a = signal.butter(2, [1200 / (grid.sr / 2), 3600 / (grid.sr / 2)], btype="band")
    rim = signal.lfilter(b, a, noise) * _env(rn, 0.001, 0.018)

    # Shaker: eighth notes, accented on the beat.
    sn = grid.samples(0.05)
    b2, a2 = signal.butter(2, 5000 / (grid.sr / 2), btype="high")
    shaker = signal.lfilter(b2, a2, rng.standard_normal(sn)) * _env(sn, 0.001, 0.012)

    for b_i in range(n_bars):
        bar_t = grid.bar_start(b_i)
        for beat in range(grid.beats_per_bar):
            at = grid.samples(bar_t + beat * grid.beat)
            if beat % 2 == 0:
                _add(out, kick * 0.55, at)
            else:
                _add(out, rim * 0.16, at)
            for eighth in (0.0, 0.5):
                gain = 0.06 if eighth == 0.0 else 0.035
                _add(out, shaker * gain * rng.uniform(0.8, 1.2),
                     grid.samples(bar_t + (beat + eighth) * grid.beat))
    return out


def _bells(grid: Grid, n_bars: int, rng: np.random.Generator) -> np.ndarray:
    """Sparse pentatonic plucks — anything pentatonic fits any chord here."""
    total = grid.samples(n_bars * grid.bar) + grid.sr
    out = np.zeros(total)
    n = grid.samples(1.6)
    t = np.arange(n) / grid.sr
    for b_i in range(n_bars):
        if rng.random() > 0.55:
            continue
        for _ in range(rng.integers(1, 3)):
            beat = rng.integers(0, grid.beats_per_bar * 2) / 2
            note = PENTATONIC[rng.integers(0, len(PENTATONIC))]
            f = _midi_hz(note)
            sig = (np.sin(2 * np.pi * f * t) + 0.3 * np.sin(2 * np.pi * 2 * f * t)
                   + 0.12 * np.sin(2 * np.pi * 3 * f * t))
            sig *= _env(n, 0.006, 0.5) * rng.uniform(0.05, 0.11)
            _add(out, sig, grid.samples(grid.bar_start(b_i) + beat * grid.beat))
    return out


def render_bed(grid: Grid, n_bars: int, seed: int = 0) -> np.ndarray:
    """Render `n_bars` of backing music. Returns stereo float32, shape (n, 2)."""
    rng = np.random.default_rng(seed)
    pad = _reverb(_pad(grid, n_bars, rng), seconds=3.0, mix=0.45, rng=rng)
    bells = _reverb(_bells(grid, n_bars, rng), seconds=2.4, mix=0.5, rng=rng)
    mono = pad * 0.55 + _bass(grid, n_bars) * 0.5 + _drums(grid, n_bars, rng) + bells

    # Fade the very start and end so the track does not click in or out.
    fade = grid.samples(min(grid.bar * 2, len(mono) / grid.sr / 3))
    mono[:fade] *= np.linspace(0, 1, fade)
    mono[-fade:] *= np.linspace(1, 0, fade)

    # A short Haas delay on one side widens the pad without smearing the beat.
    delay = grid.samples(0.012)
    left = mono
    right = np.concatenate([np.zeros(delay), mono])[: len(mono)]
    stereo = np.stack([left, 0.85 * right + 0.15 * left], axis=1)
    peak = np.abs(stereo).max()
    if peak > 0:
        stereo = stereo / peak * 0.7
    return stereo.astype(np.float32)
