"""Procedural ambient bed.

The bed is synthesised rather than generated by a model so that the beat grid is
known by construction — every downbeat lands exactly where we put it, which is
what the arranger needs. See DESIGN.md for the alternatives.

Everything that shapes the sound lives in a BedSpec (see bedspec.py); this
module only renders it.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from scipy import signal

from .bedspec import BedSpec
from .instruments import build as build_instrument

SR = 44100


@dataclass(frozen=True)
class Grid:
    """A metrical grid. All times in seconds."""

    bpm: float = 80.0
    beats_per_bar: int = 4
    beat_unit: int = 4
    swing: float = 0.0
    sr: int = SR

    @classmethod
    def from_spec(cls, spec: BedSpec) -> "Grid":
        return cls(bpm=spec.bpm, beats_per_bar=spec.beats_per_bar,
                   beat_unit=spec.beat_unit, swing=spec.swing)

    @property
    def beat(self) -> float:
        return 60.0 / self.bpm * 4 / self.beat_unit

    @property
    def bar(self) -> float:
        return self.beat * self.beats_per_bar

    @property
    def steps_per_bar(self) -> int:
        steps = self.beats_per_bar * 16 / self.beat_unit
        if steps != int(steps):
            raise ValueError("Meter must divide cleanly into sixteenth notes.")
        return int(steps)

    def bar_start(self, index: int) -> float:
        return index * self.bar

    def step_time(self, bar: int, step: int) -> float:
        """Time of a 16th-note step, with swing applied to the off-eighths."""
        offset = step / self.steps_per_bar * self.bar
        if self.swing and step % 4 == 2:
            offset += self.swing * (self.bar / self.steps_per_bar)
        return self.bar_start(bar) + offset

    def samples(self, seconds: float) -> int:
        return int(round(seconds * self.sr))


def _midi_hz(note: float) -> float:
    return 440.0 * 2 ** ((note - 69) / 12.0)


def _env(n: int, attack: float, decay: float, sr: int = SR) -> np.ndarray:
    """Percussive attack/exponential-decay envelope."""
    t = np.arange(n) / sr
    a = np.clip(t / max(attack, 1e-4), 0, 1)
    return a * np.exp(-t / max(decay, 1e-4))


def _add(buf: np.ndarray, sig: np.ndarray, at: int) -> None:
    end = min(len(buf), at + len(sig))
    if end > at:
        buf[at:end] += sig[: end - at]


def _onepole_lp(x: np.ndarray, cutoff: float, sr: int = SR) -> np.ndarray:
    b, a = signal.butter(2, min(cutoff / (sr / 2), 0.99), btype="low")
    return signal.lfilter(b, a, x)


def filter_curve(spec: BedSpec, n_bars: int, points: int,
                 rng: np.random.Generator) -> np.ndarray:
    """Return the pad cutoff automation curve at an arbitrary control rate."""
    bars = np.linspace(0, n_bars, points, endpoint=False)
    period = max(spec.pad.cutoff_period_bars, 0.25)
    phase = 2 * np.pi * bars / period
    if spec.pad.cutoff_curve == "sine":
        shape = np.sin(phase)
    elif spec.pad.cutoff_curve == "triangle":
        shape = signal.sawtooth(phase, width=0.5)
    elif spec.pad.cutoff_curve == "random_walk":
        anchors = max(int(np.ceil(n_bars)) + 1, 2)
        walk = np.cumsum(rng.normal(0, 0.45, anchors))
        walk -= walk.mean()
        peak = np.abs(walk).max()
        if peak:
            walk /= peak
        shape = np.interp(bars, np.linspace(0, n_bars, anchors), walk)
    else:
        raise ValueError(f"Unknown filter curve '{spec.pad.cutoff_curve}'.")
    cutoff = spec.pad.cutoff_base + spec.pad.cutoff_motion * shape
    return np.clip(cutoff, 120.0, SR * 0.45)


def _automated_lp(x: np.ndarray, spec: BedSpec, n_bars: int,
                  rng: np.random.Generator, block: int = 2048) -> np.ndarray:
    """Low-pass in short stateful blocks to avoid zippering between cutoffs."""
    if not len(x):
        return x
    n_blocks = int(np.ceil(len(x) / block))
    cutoffs = filter_curve(spec, n_bars, n_blocks, rng)
    out = np.zeros_like(x)
    state = None
    for index, cutoff in enumerate(cutoffs):
        start = index * block
        end = min(len(x), start + block)
        sos = signal.butter(2, min(cutoff / (SR / 2), 0.99),
                            btype="low", output="sos")
        if state is None:
            state = signal.sosfilt_zi(sos) * x[start]
        out[start:end], state = signal.sosfilt(sos, x[start:end], zi=state)
    return out


def _reverb(x: np.ndarray, seconds: float = 2.2, mix: float = 0.35, sr: int = SR,
            rng: np.random.Generator | None = None) -> np.ndarray:
    """Convolution reverb against a synthetic exponentially-decaying noise IR."""
    rng = rng or np.random.default_rng(0)
    n = int(seconds * sr)
    t = np.arange(n) / sr
    ir = rng.standard_normal(n) * np.exp(-t * (5.0 / seconds))
    ir[: int(0.02 * sr)] *= np.linspace(0, 1, int(0.02 * sr))  # soften pre-delay
    ir = _onepole_lp(ir, 4000.0, sr)
    ir /= np.abs(ir).sum() / 8
    wet = signal.fftconvolve(x, ir)[: len(x)]
    return (1 - mix) * x + mix * wet


def _blank(grid: Grid, n_bars: int) -> np.ndarray:
    return np.zeros(grid.samples(n_bars * grid.bar) + grid.sr)


def _pad(spec: BedSpec, grid: Grid, n_bars: int, rng: np.random.Generator) -> np.ndarray:
    """Sustained chord wash, one chord per bar, overlapping into the next."""
    out = _blank(grid, n_bars)
    if not spec.pad.enabled:
        return out
    dur = grid.bar * spec.pad.overlap
    n = grid.samples(dur)
    t = np.arange(n) / grid.sr
    # Slow swell in, slow fall away.
    env = np.sin(np.pi * np.clip(t / dur, 0, 1)) ** 1.5

    instrument = build_instrument(spec.pad.instrument)
    for b in range(n_bars):
        chord = spec.chord(spec.progression[b % len(spec.progression)])
        voice = np.zeros(n)
        if spec.pad.instrument == "synth":
            for note in chord:
                for detune in (-spec.pad.detune, 0.0, spec.pad.detune):
                    f = _midi_hz(note + detune)
                    phase = rng.uniform(0, 2 * np.pi)
                    voice += np.sin(2 * np.pi * f * t + phase) / (
                        1 + 0.5 * (note - spec.root) / 12)
            voice /= len(chord) * 3
        else:
            for note in chord:
                _add(voice, instrument.render(note, 0.55, dur), 0)
            voice /= max(len(chord), 1)
        _add(out, voice * env, grid.samples(grid.bar_start(b)))
    return _automated_lp(out, spec, n_bars, rng) * spec.pad.level


def _bass(spec: BedSpec, grid: Grid, n_bars: int) -> np.ndarray:
    out = _blank(grid, n_bars)
    if not spec.bass.enabled:
        return out
    n = grid.samples(grid.bar * 0.9)
    t = np.arange(n) / grid.sr
    env = (np.clip(t / max(spec.bass.attack, 1e-3), 0, 1)
           * np.exp(-t / (grid.bar * spec.bass.decay_bars)))
    for b in range(n_bars):
        degree = spec.progression[b % len(spec.progression)]
        f = _midi_hz(spec.chord_root(degree) + 12 * spec.bass.octave)
        sig = (np.sin(2 * np.pi * f * t) + 0.25 * np.sin(4 * np.pi * f * t)) * env
        _add(out, sig, grid.samples(grid.bar_start(b)))
    return out * spec.bass.level


def _drums(spec: BedSpec, grid: Grid, n_bars: int,
           rng: np.random.Generator) -> np.ndarray:
    out = _blank(grid, n_bars)
    if not spec.drums.enabled:
        return out

    # Soft sub kick with a pitch drop.
    kn = grid.samples(0.35)
    kt = np.arange(kn) / grid.sr
    kick = np.sin(2 * np.pi * np.cumsum(55 * np.exp(-kt * 18) + 34) / grid.sr)
    kick *= _env(kn, 0.002, 0.12)

    # Rimshot: short filtered noise burst.
    rn = grid.samples(0.06)
    b, a = signal.butter(2, [1200 / (grid.sr / 2), 3600 / (grid.sr / 2)], btype="band")
    rim = signal.lfilter(b, a, rng.standard_normal(rn)) * _env(rn, 0.001, 0.018)

    # Shaker on the eighths, accented on the beat.
    sn = grid.samples(0.05)
    b2, a2 = signal.butter(2, 5000 / (grid.sr / 2), btype="high")
    shaker = signal.lfilter(b2, a2, rng.standard_normal(sn)) * _env(sn, 0.001, 0.012)

    for bar in range(n_bars):
        for step in range(grid.steps_per_bar):
            at = grid.samples(grid.step_time(bar, step))
            if spec.drums.kick[step % len(spec.drums.kick)] != ".":
                _add(out, kick * spec.drums.kick_level, at)
            if spec.drums.rim[step % len(spec.drums.rim)] != ".":
                _add(out, rim * spec.drums.rim_level, at)
            if step % 2 == 0 and rng.random() < spec.drums.shaker_density:
                accent = 1.0 if step % 4 == 0 else 0.6
                _add(out, shaker * spec.drums.shaker_level * accent
                     * rng.uniform(0.8, 1.2), at)
    return out


def _lead(spec: BedSpec, grid: Grid, n_bars: int,
          rng: np.random.Generator) -> np.ndarray:
    """Sparse pentatonic notes — anything pentatonic fits every chord here."""
    out = _blank(grid, n_bars)
    if not spec.lead.enabled:
        return out
    instrument = build_instrument(spec.lead.instrument)
    notes = spec.pentatonic()
    lo, hi = spec.lead.velocity

    for bar in range(n_bars):
        if rng.random() > spec.lead.bar_probability:
            continue
        for _ in range(int(rng.integers(1, spec.lead.max_notes + 1))):
            step = int(rng.integers(0, max(grid.steps_per_bar // 2, 1))) * 2
            note = notes[int(rng.integers(0, len(notes)))]
            velocity = float(rng.uniform(lo, hi))
            jitter = rng.uniform(-spec.lead.humanize, spec.lead.humanize) \
                if spec.lead.humanize else 0.0
            at = grid.samples(max(0.0, grid.step_time(bar, step) + jitter))
            _add(out, instrument.render(note, velocity, 1.6), at)
    return out * spec.lead.level * 0.11


def _stereo(mono: np.ndarray, grid: Grid) -> np.ndarray:
    """Widen one stem with a short Haas delay without smearing its beat."""
    delay = grid.samples(0.012)
    right = np.concatenate([np.zeros(delay), mono])[: len(mono)]
    return np.stack([mono, 0.85 * right + 0.15 * mono], axis=1)


def render_stems(spec: BedSpec, n_bars: int) -> dict[str, np.ndarray]:
    """Render named stereo stems without bus peak normalisation."""
    grid = Grid.from_spec(spec)
    rng = np.random.default_rng(spec.seed)
    space = spec.space

    pad = _reverb(_pad(spec, grid, n_bars, rng),
                  seconds=space.reverb_seconds, mix=space.reverb_mix, rng=rng)
    lead = _reverb(_lead(spec, grid, n_bars, rng),
                   seconds=space.reverb_seconds * 0.8,
                   mix=min(space.reverb_mix + 0.05, 0.7), rng=rng)
    stems = {
        "pad": pad,
        "bass": _bass(spec, grid, n_bars),
        "drums": _drums(spec, grid, n_bars, rng),
        "lead": lead,
    }

    # Fade the very start and end so the track does not click in or out.
    for mono in stems.values():
        fade = grid.samples(min(grid.bar * 2, len(mono) / grid.sr / 3))
        mono[:fade] *= np.linspace(0, 1, fade)
        mono[-fade:] *= np.linspace(1, 0, fade)
    return {name: _stereo(mono, grid).astype(np.float32)
            for name, mono in stems.items()}


def render_bed(spec: BedSpec, n_bars: int) -> np.ndarray:
    """Render and sum `n_bars` of backing music as stereo float32."""
    stems = render_stems(spec, n_bars)
    stereo = sum(stems.values(), np.zeros_like(next(iter(stems.values()))))
    peak = np.abs(stereo).max()
    if peak > 0:
        stereo = stereo / peak * 0.7
    return stereo.astype(np.float32)
